FROM armhf/golang:1.6
RUN go get github.com/rancher/trash
ENV DAPPER_SOURCE /go/src/github.com/rancher/rancher-net/
ENV DAPPER_OUTPUT bin dist
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
