#!/bin/bash
### BEGIN INIT INFO
# Provides:		rancher-net
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	rancher-net - Rancher Networking server
# Description:		rancher-net - Rancher Networking server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CATTLE_HOME=${CATTLE_HOME:-/var/lib/cattle}
export PIDFILE=/var/run/rancher-net.pid
RUNDIR=$CATTLE_HOME
DAEMON=$RUNDIR/bin/rancher-net
RUNNING_DAEMON=$CATTLE_HOME/bin/rancher-net
DAEMON_ARGS="--log /var/log/rancher-net.log -f ${CATTLE_HOME}/etc/cattle/ipsec/config.json -c ${CATTLE_HOME}/etc/cattle/ipsec -i $(ip route get 8.8.8.8 | grep via | awk '{print $7}')/16 --pid-file ${PIDFILE}"
NAME=rancher-net
DESC=rancher-net
GCM=false

if [ ! -x $DAEMON ]; then
    chmod +x $DAEMON
fi

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	for ((i=0; i<6; i++)); do
		if ip xfrm state add src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp mode tunnel aead "rfc4106(gcm(aes))" 0x0000000000000000000000000000000000000001 128 sel src 1.1.1.1 dst 1.1.1.1; then
			GCM=true
			ip xfrm state del src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp 2>/dev/null || true
			break
		fi
		ip xfrm state del src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp 2>/dev/null || true
		sleep 1
	done

	DAEMON_ARGS="$DAEMON_ARGS --gcm=$GCM"

	if ! $CATTLE_HOME/bin/rancher-net --test-charon; then
	    # If we can't talk to charon, restart it
	    killall -9 charon || true
	fi

	log_daemon_msg "Starting $DESC configuration" "$NAME" || true
	mkdir -p $RUNDIR

	if start-stop-daemon --start -b --quiet -d $RUNDIR --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping $DESC configuration" "$NAME" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $RUNNING_DAEMON
	then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	rm -f $PIDFILE
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  reload|force-reload)
	log_daemon_msg "Reloading $DESC configuration" "$NAME" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile $PIDFILE --exec $RUNNING_DAEMON; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
