#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..
mkdir -p bin
echo Building version $VERSION
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION" -o bin/rancher-net main.go
