#!/bin/bash
set -e

cd $(dirname $0)/..

VERSION=5.4.0-1
VARIANT=_arm
HASH=907de47b24370adf7ac3f254dc2ab4bbbd221991

if [ "$(sha1sum -b strongswan/strongswan-${VERSION}${VARIANT}.tar.gz | awk '{print $1}')" != "$HASH" ]; then
    mkdir -p strongswan
    curl -L https://github.com/imikushin/strongswan-package/releases/download/v${VERSION}/strongswan-${VERSION}${VARIANT}.tar.gz > strongswan/strongswan-${VERSION}${VARIANT}.tar.gz
    [ "$(sha1sum -b strongswan/strongswan-${VERSION}${VARIANT}.tar.gz | awk '{print $1}')" == "$HASH" ]
fi
