#!/bin/bash

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package

IMAGE_TAG=${IMAGE_TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if $(echo ${IMAGE_TAG} | grep -q dirty); then
    IMAGE_TAG=dev
fi

cp ../bin/rancher-net .
cp ../strongswan/* strongswan.tar.gz
docker build -t ${REPO}/net:${IMAGE_TAG} .

echo Built ${REPO}/net:${IMAGE_TAG}
