#!/bin/bash

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if $(echo ${TAG} | grep -q dirty); then
    TAG=dev
fi

cp ../bin/rancher-net .
cp ../strongswan/* strongswan.tar.gz
docker build -t ${REPO}/net:${TAG} .

echo Built ${REPO}/net:${TAG}
